### ISSUE TITLE
[Bug] Meet error ModuleNotFoundError: No module named 'tvm.sparse' on runtime

### ISSUE THREAD

**Issue by azazhu** [uwsampl/SparseTIR#79]
Did I use a wrong TVM version?
![image](https://user-images.githubusercontent.com/16014148/207486291-607ca387-6cca-4fdf-903f-07f9417e93a2.png)

### Expected behavior

Run examples/spmm/bench_spmm_naive.py successfully

### Actual behavior

Met following error:
[01:56:18] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /venv/apache-tvm-py3.7/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.12.0.so: cannot open shared object file: No such file or directory
Using backend: pytorch
Traceback (most recent call last):
  File "examples/spmm/bench_spmm_naive.py", line 27, in <module>
    from tvm.sparse import FormatRewriteRule, lower_sparse_buffer, lower_sparse_iter
ModuleNotFoundError: No module named 'tvm.sparse'

### Environment

Ubuntu 18.04.6 LTS
TVM: 0.11.dev0
LLVM version 14.0.0

### Steps to reproduce
1. download [and mv](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-aarch64-linux-gnu.tar.xz) and setup PATH 
2. build tvm from tvm repo
3. build sparseTIR

**Comment by yzh119** [comment]
After you compile the source code (in C++), you should either install the python package via
```bash
python3 python/setup.py install
```
or set environment variable `PYTHONPATH`:
```bash
export PYTHONPATH=${YOUR_SPARSETIR_DIR}/python:${PYTHONPATH}
```

**Comment by yzh119** [comment]
btw, you shouldn't build tvm from tvm repo, SparseTIR is a fork of TVM and is self-contained.

**Comment by azazhu** [comment]
export PYTHONPATH can work. "python3 python/setup.py install" fails with following error:
 `root@84eaf74fddb8:/workspace2/sparsetir# python3 python/setup.py install
WARNING:root:git describe: fatal: detected dubious ownership in repository at '/workspace2/sparsetir'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspace2/sparsetir
, use 0.9.dev0
Traceback (most recent call last):
  File "python/setup.py", line 251, in <module>
    ext_modules=config_cython(),
  File "python/setup.py", line 133, in config_cython
    for fn in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'tvm/_ffi/_cython'
`
I think it is due to using a wrong tvm version.
BTW, where is self-contained tvm in sparseTIR? is it in docker image or submodules?

**Comment by azazhu** [comment]
It works now. Thx Zihao. This issue can be closed.
